# Generated by Django 6.1 on 2026-08-31 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0002_alter_attendance_status_and_more'),
        ('classesApp', '0003_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classesApp.classroom'),
        ),
    ]
