# Generated by Django 6.1 on 2026-08-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total course fees', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Paid amount', max_digits=10),
        ),
    ]
