# Generated by Django 6.1 on 2026-09-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked', max_digits=5),
        ),
    ]
