# Generated by Django 6.1 on 2026-09-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0003_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Course fees for this class', max_digits=10),
        ),
    ]
