# Generated by Django 6.1 on 2026-09-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersApp', '0003_remove_teacher_subject_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate for payment', max_digits=10),
        ),
    ]
